import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import { ApolloWrapper } from "@/graphql/apolloWrapper";
import { CookiesProvider } from "next-client-cookies/server";
import "@/styles/globals.scss";

const notoSansKr = Noto_Sans_KR({
  weight: ["400", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <CookiesProvider>
          <ApolloWrapper>{children}</ApolloWrapper>
        </CookiesProvider>
      </body>
    </html>
  );
}
