import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";
import styles from "./layout.module.scss";
import Header from "@/app/(afterLogin)/_component/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
